kind: pipeline
name: default

workspace:
 base: /go
 path: src/github.com/stars-dream/helloworld

steps:
- name: develop
  image: dev-harbor.teyixing.com/public/golang:latest
  commands:
  - go get
  - go test
  - go run helloworld.go
  - go build
  when:
    event:
    - push
    - pull-request